### ISSUE TITLE
Cannot generate over 20 pages

### ISSUE THREAD

**Issue by gabucito** [pdfmake/pdfmake#15]
I believe this is a bug that has been present in the original pdfmake and it was never really resolved bpampuch/pdfmake#464.

Everything works fine until you reach 17+ pages and it really takes a toll in performance.  I found that chrome just won't open the pdf at 20+ pages, firefox opens it somehow but gives you an alert about the script being unresponsive.

**Comment by tsiegleauq** [comment]
cannot really comprehend.
generating 40 pages takes
23 seconds for me.

`Modellname:            Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
Stepping:              3
CPU MHz:               1067.358
`

javascript still does not support multi-threading. And a lot of stuff happens during PDF generations. Waiting some time seems totally reasonable to me.

If you really want this problem solved you might elaborate on this issue a little more.

**Comment by gine** [comment]
Applying this patch you can resolve:
https://github.com/bpampuch/pdfmake/issues/280#issuecomment-98944706

**Comment by gabucito** [comment]
@gine Thank you, I implemented the solution given in that issue.  Sadly I found out that the actual code is generated from the nodejs repo and hence cannot really be fixed in this library (unless you manually implment the fix after building).

Will be closing this issue.
