### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by tsiegleauq** [pdfmake/pdfmake#16]
Hi.
You might did not notice:

@emanuelschuetze
> @miltador Is it possible that you can make a new release ( 0.1.31) in the next days? We need this fix for transparent PNGs in an official pdfmake release asap. Thanks in advance.

([compare](https://github.com/pdfmake/pdfmake/pull/14))

Is it possible to release a new version with the current build of grunt-browserify?

Thanks a lot!

**Comment by slavko-ptitsyn** [comment]
Hi! Also need this fix. Can you make a release, please.

**Comment by magnusekstrand** [comment]
Also need this fix. Is there a date set for next release?

**Comment by tsiegleauq** [comment]
If you guys are in REALLY desperate need for this fix and need it right now you can use [my release](https://github.com/tsiegleauq/pdfmake/releases/tag/v0.1.30.1) untill @miltador releases a new version.

**Comment by miltador** [comment]
Hi all!
Sorry for such a long delay, was very busy with my work.
New version is out, built with grunt-browserify 5.0.0.
I'll try to migrate to pdfkit 0.8.0 next.
